### ISSUE TITLE
What's the performance when CNN is also trained?

### ISSUE THREAD

**Issue by Juna2** [laura-rieger/deep-explanation-penalization#6]
Hi, Laura.
I found that with the vgg16 you trained with the ISIC dataset, actual training only happens on the FC layer at the end.
Have you tried training all the layers as well?
Thanks in advance!

**Comment by laura-rieger** [comment]
Hi,
we tried training the entire net (without CDEP or any other regularization) on the ISIC dataset. The performance was below training only the FC layers and the model overfit, presumably because the dataset is relatively small for training an entire vgg16. Therefore we focused on finetuning the last layers in our experiments.

**Comment by Juna2** [comment]
Thank you for the information! Have a good day!
