### ISSUE TITLE
Hyperparameter of ColorMNIST

### ISSUE THREAD

**Issue by Juna2** [laura-rieger/deep-explanation-penalization#7]
Hi, Laura.
I found that the performance(Test accuracy=23.41%) of CDEP that the jupyter notebook in this repo says in ColorMNIST dataset is different from the one in ICML paper(Test accuracy=31.0%).
So could you tell me the hyperparameters that you use to get the performance? (lr, lambda, batch_size, seed)
Thanks a lot!

**Comment by laura-rieger** [comment]
Hi Jeon,

thanks for catching that! The demo indeed uses lambda = 1000, in the main paper we use 5000 (fig S2 in the appendix shows the progression).  I fixed that in the repo.
Results in the paper were averaged over thirty seeds, I set a fixed demo seed now. 
It also seems I was too enthusiastic while refactoring for the camera-ready so that test accuracy was not calculated with the best dev weights. I just fixed that. You can just pull the repo again.

Best, Laura

**Comment by Juna2** [comment]
Thank you for the information!

**Comment by avani17101** [comment]
could you tell the value of penalization rate used for experimentation of colormnist in paper?  @laura-rieger

**Comment by laura-rieger** [comment]
Hi, I think 10^4 should be right. Best, Laura

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
